sudo: required
services:
  - docker

before_install:
  - docker build -t manomit/multi-docker-demo -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true manomit/multi-docker-demo npm run test

after_success:
  - docker build -t manomit/multi-client ./client
  - docker build -t manomit/multi-nginx ./nginx
  - docker build -t manomit/multi-server ./server
  - docker build -t manomit/multi-worker ./worker
